#spring:
  #cloud:
    #config:
      #server:
        #git:
          #uri: https://github.com/xxce10xx/cursoExpert  #application:    #name: config
#HTTP Server
#server:  #port: 4444

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xxce10xx/cursoExpert
          repos:
            developper:
              pattern:
                - '*/dev'
              uri: https://github.com/xxce10xx/pruebacjava
              
#HTTP Server
server:
  port: 4444